version: '3.1'
services:
  db:
    image: mariadb:10.3
    container_name: DB_host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin
    container_name: DB_interface
    restart: always
    ports:
      - 3306:80
    platform: linux/amd64
    environment:
      - PMA_HOST=DB_host
    depends_on:
      - db
    networks:
      - mynetwork

  web:
    image: nginx
    container_name: web_server
    volumes:
      - "~/source/brendon/ci:/usr/share/nginx/html/ci"
      - "./nginx_config/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - mynetwork

  redis:
    image: redis
    container_name: redis
    networks:
      - mynetwork

  php:
    container_name: php
    build: ./php
    volumes:
      - "~/source/brendon/ci:/usr/share/nginx/html/ci"
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
